/**
 * Genkit AI Service — Ported 100% from editor/src/genkit/
 *
 * Files ported:
 * - chat-flow.ts  → chatFlow (stream-based AI chat with 16 tools)
 * - tools.ts      → getTools() (all 16 agentic tools)
 * - utils.ts      → buildAssetInstruction(), buildMessageContent()
 * - type.ts       → ImportAsset interface
 * - script-to-video-flow.ts → scriptToVideoFlow
 * - script-to-video-tools.ts → getScriptToVideoTools()
 *
 * Only provider change: @genkit-ai/google-genai → @genkit-ai/vertexai
 * All tool definitions, system prompts, and streaming logic are IDENTICAL to original.
 */
import { genkit, z } from 'genkit';
import { vertexAI } from '@genkit-ai/vertexai';
import type { Part } from 'genkit';

// --- Type ported from editor/src/genkit/type.ts ---

interface TimeRange {
  from: number;
  to: number;
}

export interface ImportAsset {
  assetId: string;
  type: 'import';
  assetType: string;
  text: string;
  url: string;
  label: string;
  trackId: string;
  display: TimeRange;
  trim?: TimeRange;
}

// --- Initialize Genkit with Vertex AI (replacing Google AI) ---

export const ai = genkit({
  plugins: [vertexAI()],
  model: vertexAI.model('gemini-2.5-flash-lite'),
});

// --- Utils ported from editor/src/genkit/utils.ts (100% identical) ---

export function buildAssetInstruction(asset: ImportAsset, isSelected: boolean) {
  const { assetId, assetType, display, trim, text, label } = asset;

  const name = label || assetId;
  const tag = isSelected ? '[SELECTED]' : '[EXISTING]';

  const displayFrom = (display.from / 1000).toFixed(2);
  const displayTo = (display.to / 1000).toFixed(2);

  let instruction = `
ASSET_CONTEXT ${tag}
- id: ${assetId}
- name: "${name}"
- type: ${assetType}
- timeline: appears from ${displayFrom}s to ${displayTo}s
`.trim();

  if (assetType === 'text' && text) {
    instruction += `
- content: "${text}"
- role: on-screen text element
`.trim();
  }

  if ((assetType === 'video' || assetType === 'audio') && trim) {
    const trimFrom = (trim.from / 1000).toFixed(2);
    const trimTo = (trim.to / 1000).toFixed(2);

    instruction += `
- source_usage: uses source segment from ${trimFrom}s to ${trimTo}s
- role: time-based media asset
`.trim();
  }

  if (assetType === 'image') {
    instruction += `
- role: static visual element
- behavior: displayed as a still image during its timeline range
`.trim();
  }

  instruction += `
- note: this asset is referenced by its id (${assetId}) in the media content provided to you
`.trim();

  return instruction;
}

export function buildMessageContent(assets: ImportAsset[]): Part[] {
  const sortedAssets = assets
    .slice()
    .sort((a, b) => a.display.from - b.display.from);
  const content: Part[] = [];

  sortedAssets.forEach((asset) => {
    if (asset.assetType === 'text' && asset.text) {
      content.push({ text: asset.text });
    } else if (asset.assetType === 'video') {
      const trimFrom = asset.trim
        ? (asset.trim.from / 1000).toFixed(2)
        : '0.00';
      const trimTo = asset.trim ? (asset.trim.to / 1000).toFixed(2) : 'full';
      content.push({
        text: `Video id: ${asset.assetId}. Use only the segment from ${trimFrom} to ${trimTo}`,
      });
      if (asset.url) {
        content.push({ media: { contentType: 'video/mp4', url: asset.url } });
      }
    } else if (asset.assetType === 'audio') {
      const trimFrom = asset.trim
        ? (asset.trim.from / 1000).toFixed(2)
        : '0.00';
      const trimTo = asset.trim ? (asset.trim.to / 1000).toFixed(2) : 'full';
      content.push({
        text: `Audio id: ${asset.assetId}. Use only the segment from ${trimFrom} to ${trimTo}`,
      });
      if (asset.url) {
        content.push({ media: { contentType: 'audio/mp3', url: asset.url } });
      }
    } else if (asset.assetType === 'image') {
      content.push({
        text: `Image id: ${asset.assetId}. Display from ${(asset.display.from / 1000).toFixed(2)}s to ${(asset.display.to / 1000).toFixed(2)}s`,
      });
      if (asset.url) {
        content.push({ media: { url: asset.url } });
      }
    }
  });

  return content;
}

// --- Tools ported from editor/src/genkit/tools.ts (100% identical logic) ---

let toolsCache: any[] | null = null;

export function getTools() {
  if (toolsCache) return toolsCache;

  const add_text = ai.defineTool(
    {
      name: 'add_text',
      description: 'Add a text element to the video timeline',
      inputSchema: z.object({
        text: z.string().describe('The text content to display'),
        targetId: z
          .string()
          .optional()
          .describe('The unique ID for this new asset (generated by you)'),
        from: z
          .number()
          .default(0)
          .describe('Start time in seconds (default 0)'),
        to: z.number().default(5).describe('End time in seconds (default 0)'),
      }),
      outputSchema: z.object({ targetId: z.string(), message: z.string() }),
    },
    async ({ text, targetId, from, to }) => {
      console.log('text: ', { text, targetId, from, to });
      return {
        targetId: targetId || 'temp_id',
        message: `Text added: ${text}`,
      };
    }
  );

  const add_image = ai.defineTool(
    {
      name: 'add_image',
      description: 'Generate an image or add an image based on a prompt',
      inputSchema: z.object({
        prompt: z
          .string()
          .describe('Detailed description of the image to generate or add'),
        url: z.string().optional().describe('URL of the image if available'),
        targetId: z
          .string()
          .optional()
          .describe('The unique ID for this new asset'),
        from: z
          .number()
          .default(0)
          .describe('Start time in seconds (default 0)'),
        to: z.number().default(5).describe('End time in seconds (default 0)'),
      }),
      outputSchema: z.object({ targetId: z.string(), message: z.string() }),
    },
    async ({ prompt, targetId }) => {
      return {
        targetId: targetId || 'temp_id',
        message: `🖼 Image created/added with prompt "${prompt}"`,
      };
    }
  );

  const add_video = ai.defineTool(
    {
      name: 'add_video',
      description: 'Add a video based on a prompt or URL',
      inputSchema: z.object({
        prompt: z.string().describe('Detailed description of the video to add'),
        url: z.string().optional().describe('URL of the video if available'),
        targetId: z
          .string()
          .optional()
          .describe('The unique ID for this new asset'),
        from: z.number().optional().describe('Start time in seconds'),
        to: z.number().optional().describe('End time in seconds'),
      }),
      outputSchema: z.object({ targetId: z.string(), message: z.string() }),
    },
    async ({ prompt, targetId }) => {
      return {
        targetId: targetId || 'temp_id',
        message: `🎬 Video added with prompt "${prompt}"`,
      };
    }
  );

  const add_audio = ai.defineTool(
    {
      name: 'add_audio',
      description: 'Add audio or music to the video',
      inputSchema: z.object({
        prompt: z.string().describe('Description of the audio or music to add'),
        url: z.string().optional().describe('URL of the audio if available'),
        targetId: z
          .string()
          .optional()
          .describe('The unique ID for this new asset'),
        from: z.number().optional().describe('Start time in seconds'),
        to: z.number().optional().describe('End time in seconds'),
      }),
      outputSchema: z.object({ targetId: z.string(), message: z.string() }),
    },
    async ({ prompt, targetId }) => {
      return {
        targetId: targetId || 'temp_id',
        message: `🎵 Audio added with prompt "${prompt}"`,
      };
    }
  );

  const update_clip = ai.defineTool(
    {
      name: 'update_clip',
      description: 'Update properties of an existing clip',
      inputSchema: z.object({
        targetId: z.string().describe('The ID of the clip to update'),
        left: z.number().optional(),
        top: z.number().optional(),
        width: z.number().optional(),
        height: z.number().optional(),
        start: z.number().optional().describe('Start time in seconds'),
        fontSize: z.number().optional().describe('Font size for text clips'),
        fontFamily: z
          .string()
          .optional()
          .describe('Font family for text clips'),
        fill: z.string().optional().describe('Text color in hex format'),
        opacity: z.number().optional().describe('Opacity from 0 to 1'),
        volume: z.number().optional().describe('Volume from 0 to 1'),
        playbackRate: z.number().optional().describe('Playback rate'),
      }),
      outputSchema: z.object({ targetId: z.string(), message: z.string() }),
    },
    async ({ targetId }) => ({ targetId, message: `Clip ${targetId} updated` })
  );

  const remove_clip = ai.defineTool(
    {
      name: 'remove_clip',
      description: 'Remove a clip from the timeline',
      inputSchema: z.object({
        targetId: z.string().describe('The ID of the clip to remove'),
      }),
      outputSchema: z.object({ targetId: z.string(), message: z.string() }),
    },
    async ({ targetId }) => ({ targetId, message: `Clip ${targetId} removed` })
  );

  const split_clip = ai.defineTool(
    {
      name: 'split_clip',
      description: 'Split a clip at a specific time',
      inputSchema: z.object({
        targetId: z.string().describe('The ID of the clip to split'),
        time: z.number().optional().describe('The time in seconds to split at'),
      }),
      outputSchema: z.object({ targetId: z.string(), message: z.string() }),
    },
    async ({ targetId, time }) => ({
      targetId,
      message: `Clip ${targetId} split at ${time} seconds`,
    })
  );

  const add_transition = ai.defineTool(
    {
      name: 'add_transition',
      description: 'Add a transition between two clips',
      inputSchema: z.object({
        fromId: z.string().describe('Source clip ID'),
        toId: z.string().describe('Target clip ID'),
        transitionType: z
          .string()
          .default('fade')
          .describe('Type of transition (e.g., fade, slide)'),
      }),
      outputSchema: z.object({ message: z.string() }),
    },
    async ({ fromId, toId, transitionType }) => ({
      message: `Transition ${transitionType} added between ${fromId} and ${toId}`,
    })
  );

  const add_effect = ai.defineTool(
    {
      name: 'add_effect',
      description: 'Add a visual effect to a clip',
      inputSchema: z.object({
        effectName: z
          .string()
          .default('glitch')
          .describe('Name of the effect (e.g., glitch, sepia)'),
        from: z.number().optional().describe('Start time in seconds'),
        to: z.number().optional().describe('End time in seconds'),
      }),
      outputSchema: z.object({
        targetId: z.string().optional(),
        message: z.string(),
      }),
    },
    async ({ effectName }) => ({ message: `Effect ${effectName} added` })
  );

  const duplicate_clip = ai.defineTool(
    {
      name: 'duplicate_clip',
      description: 'Duplicate a specific clip or the selected ones',
      inputSchema: z.object({
        targetId: z
          .string()
          .optional()
          .describe('The ID of the clip to duplicate'),
      }),
      outputSchema: z.object({ message: z.string() }),
    },
    async ({ targetId }) => ({
      message: targetId
        ? `Clip ${targetId} duplicated`
        : 'Selected clips duplicated',
    })
  );

  const trim_clip = ai.defineTool(
    {
      name: 'trim_clip',
      description: 'Trim a clip to a specific range',
      inputSchema: z.object({
        targetId: z.string().optional().describe('The ID of the clip to trim'),
        trimFrom: z
          .number()
          .describe(
            "The new start time in seconds relative to the clip's source"
          ),
      }),
      outputSchema: z.object({ message: z.string() }),
    },
    async ({ targetId, trimFrom }) => ({
      message: `Clip ${targetId || 'selected'} trimmed from ${trimFrom}`,
    })
  );

  const search_and_add_media = ai.defineTool(
    {
      name: 'search_and_add_media',
      description: 'Search for and add stock media (video/image) from Pexels',
      inputSchema: z.object({
        query: z.string().describe('Search terms for the media'),
        type: z
          .enum(['video', 'image'])
          .default('video')
          .describe('Type of media'),
        targetId: z.string().optional().describe('Unique ID for the new clip'),
        from: z.number().optional().describe('Start time in seconds'),
      }),
      outputSchema: z.object({ message: z.string() }),
    },
    async ({ query, type }) => ({
      message: `Searching for ${type} with query "${query}"`,
    })
  );

  const generate_voiceover = ai.defineTool(
    {
      name: 'generate_voiceover',
      description: 'Generate a voiceover using text-to-speech',
      inputSchema: z.object({
        text: z.string().describe('Text to convert to speech'),
        voiceId: z.string().optional().describe('Optional voice ID to use'),
        targetId: z.string().optional().describe('Unique ID for the new clip'),
        from: z.number().optional().describe('Start time in seconds'),
      }),
      outputSchema: z.object({ message: z.string() }),
    },
    async ({ text }) => ({ message: `Generating voiceover for: "${text}"` })
  );

  const seek_to_time = ai.defineTool(
    {
      name: 'seek_to_time',
      description: 'Move the playhead to a specific time',
      inputSchema: z.object({
        time: z.number().describe('Time in seconds to seek to'),
      }),
      outputSchema: z.object({ message: z.string() }),
    },
    async ({ time }) => ({ message: `Seeking to ${time} seconds` })
  );

  const generate_captions = ai.defineTool(
    {
      name: 'generate_captions',
      description: 'Generate captions for the video or specific clips',
      inputSchema: z.object({
        clipIds: z
          .array(z.string())
          .optional()
          .describe('Specific clips to transcribe'),
      }),
      outputSchema: z.object({ message: z.string() }),
    },
    async () => ({ message: 'Generating captions' })
  );

  const fallback = ai.defineTool(
    {
      name: 'fallback',
      description:
        'Use this tool when you cannot perform the requested action with the available tools.',
      inputSchema: z.object({
        friendlyMessage: z
          .string()
          .describe(
            "A friendly explanation of why the action cannot be performed, in the user's language."
          ),
      }),
      outputSchema: z.object({ success: z.boolean() }),
    },
    async () => ({ success: true })
  );

  toolsCache = [
    add_text,
    add_image,
    add_video,
    add_audio,
    update_clip,
    remove_clip,
    split_clip,
    trim_clip,
    duplicate_clip,
    add_transition,
    add_effect,
    search_and_add_media,
    generate_voiceover,
    seek_to_time,
    generate_captions,
    fallback,
  ];

  return toolsCache;
}

// --- Chat Flow ported from editor/src/genkit/chat-flow.ts (100% identical logic) ---

const CHAT_SYSTEM_PROMPT = `You are a professional Multimodal Video Assistant.
Your goal is to help users analyze, explain, and edit their video projects.

CORE CAPABILITIES:
1. ANALYSIS: Use the provided media (video, audio, images) in the conversation to explain content, describe scenes, or answer questions.
2. EDITING: Use tools to modify the project (add/remove/update clips, transitions, and effects).
3. SEARCH: Find and add stock media from Pexels.
4. AUDIO: Generate voiceovers using text-to-speech.
5. NAVIGATION: Move the playhead to specific times.

RULES:
- When asked to explain or describe, use your multimodal vision/hearing capabilities.
- When an edit is requested, use the appropriate tool.
- For NEW assets, generate a unique targetId (e.g., text_1738086000000_a7x). Default timing is 0-5s unless specified.
- Use the current playhead position [CURRENT_TIME] as a reference when adding assets if no specific time is mentioned.
- Respond naturally in the user's language. Do NOT expose internal IDs.`;

export const chatFlow = ai.defineFlow(
  {
    name: 'chatFlow',
    inputSchema: z.object({
      message: z.string(),
      history: z
        .array(
          z.object({
            role: z.enum(['user', 'model']),
            content: z.string(),
          })
        )
        .optional(),
      metadata: z
        .object({
          existingAssets: z.array(z.any()).optional(),
          selectedAssets: z.array(z.any()).optional(),
          currentTime: z
            .number()
            .optional()
            .describe('Current playhead position in seconds'),
        })
        .optional(),
    }),
    outputSchema: z.object({ reply: z.string() }),
    streamSchema: z.string(),
  },
  async ({ message, history, metadata }, { sendChunk }) => {
    const assets = metadata?.selectedAssets?.length
      ? metadata.selectedAssets
      : metadata?.existingAssets;
    const assetsContext = assets?.map((asset: any, index: number) =>
      buildAssetInstruction(asset, index === 0)
    );
    const context = (assetsContext || []).join('\n\n');

    // Build the complete messages array for multi-turn chat
    const genkitMessages: Array<{ role: 'user' | 'model'; content: any }> = [];

    // 1. Add chat history
    if (history && history.length > 0) {
      for (const h of history) {
        genkitMessages.push({
          role: h.role as 'user' | 'model',
          content: [{ text: h.content }],
        });
      }
    }

    // 2. Add current message with current time, timeline context, and multimodal assets
    const currentMessageParts: any[] = [
      {
        text: `[CURRENT_TIME]: ${metadata?.currentTime || 0}s\n\n[CONTEXT]:\n${context}\n\n[USER]: ${message}`,
      },
    ];

    if (assets?.length) {
      const assetParts = buildMessageContent(assets);
      currentMessageParts.push(...assetParts);
    }

    genkitMessages.push({
      role: 'user',
      content: currentMessageParts,
    });

    const { stream, response } = ai.generateStream({
      system: CHAT_SYSTEM_PROMPT,
      config: {
        thinkingConfig: { thinkingBudget: 2000, includeThoughts: true },
      },
      messages: genkitMessages,
      tools: getTools(),
    });

    const toolsQueue: Array<{
      id?: string;
      name: string;
      arg: any;
      response?: any;
    }> = [];

    for await (const chunk of stream) {
      if (chunk.text) {
        sendChunk(JSON.stringify({ event: 'text', text: chunk.text }));
      }

      if (chunk.role === 'model' && chunk.content) {
        for (const part of chunk.content) {
          if (part.reasoning) {
            sendChunk(
              JSON.stringify({ event: 'reasoning', text: part.reasoning })
            );
          }
          if (part.toolRequest) {
            const req = part.toolRequest;
            const existing = toolsQueue.find((t) => {
              if (req.ref && t.id) return t.id === req.ref;
              return (
                t.name === req.name &&
                JSON.stringify(t.arg) === JSON.stringify(req.input)
              );
            });
            if (existing) {
              existing.arg = req.input;
              if (req.ref) existing.id = req.ref;
            } else {
              toolsQueue.push({ id: req.ref, name: req.name, arg: req.input });
            }
          }
        }
      }

      if (chunk.role === 'tool' && chunk.content) {
        for (const part of chunk.content) {
          if (part.toolResponse) {
            const res = part.toolResponse;
            const tool = toolsQueue.find((t) => {
              if (res.ref && t.id) return t.id === res.ref;
              return t.name === res.name && t.response === undefined;
            });
            if (tool) tool.response = res.output;
          }
        }
      }
    }

    for (const tool of toolsQueue) {
      sendChunk(
        JSON.stringify({
          event: 'tool',
          name: tool.name,
          arg: tool.arg,
          response: tool.response,
        })
      );
    }

    const { text } = await response;
    return { reply: text };
  }
);

// --- Script-to-Video Tools ported from editor/src/genkit/script-to-video-tools.ts ---

let s2vToolsCache: any[] | null = null;

function getScriptToVideoTools() {
  if (s2vToolsCache) return s2vToolsCache;

  const update_video_config = ai.defineTool(
    {
      name: 'update_video_config',
      description:
        'Update the video script and generation parameters based on user input.',
      inputSchema: z.object({
        script: z.string().describe('The video script content.'),
        aspectRatio: z
          .string()
          .optional()
          .describe(
            "The aspect ratio of the video (e.g., '16:9', '9:16', '1:1')."
          ),
        visualType: z
          .string()
          .optional()
          .describe(
            "The type of visuals to use ('AI_VIDEOS', 'AI_IMAGES', 'STOCK_VIDEOS')."
          ),
        visualStyle: z
          .string()
          .optional()
          .describe('The visual style (e.g., Cinematic, Anime, Realism).'),
        voiceId: z.string().optional().describe('The ID of the voice to use.'),
        duration: z
          .string()
          .optional()
          .describe("The duration of the video in seconds ('30', '45', '60')."),
        quality: z
          .string()
          .optional()
          .describe("The video quality ('regular', 'high')."),
        captionPosition: z
          .string()
          .optional()
          .describe("The position of captions ('top', 'middle', 'bottom')."),
        captionSize: z
          .string()
          .optional()
          .describe("The size of captions ('small', 'medium', 'large')."),
      }),
      outputSchema: z.object({ message: z.string() }),
    },
    async () => ({ message: 'Video configuration updated.' })
  );

  s2vToolsCache = [update_video_config];
  return s2vToolsCache;
}

// --- Script-to-Video Flow ported from editor/src/genkit/script-to-video-flow.ts ---

const S2V_SYSTEM_PROMPT = `You are a script-to-video assistant. Your goal is to help users create and refine scripts for their videos and configure generation parameters.

When a user provides a topic, brainstorm a creative and engaging script.

SOCIAL MEDIA VIDEO BEST PRACTICES:
- THE HOOK (0-3s): Start with a high-impact sentence or visual to stop the scroll.
- VALUE/STORY: Keep the content focused on ONE core message or tip. Use fast-paced, concise language.
- CALL TO ACTION (CTA): End with a clear instruction.

FORMATTING GUIDELINES for Script:
- Use the following scene-based format:
Scene [Number]
Narrator: [The spoken dialogue or text overlay]
Visuals: [Description of the visuals for this scene]

- Separate each scene block with a blank line.
- Do NOT include timestamps or markdown symbols like ** in the script.

CORE GUIDELINES:
- Always try to write scripts that are engaging and optimized for the chosen aspect ratio.
- If the user asks for a script, provide it in the chat using the Scene/Narrator/Visuals format.
- ALSO call update_video_config to update the hidden script field in the UI.
- Use the update_video_config tool whenever the user wants to adjust any generation parameter.
- Maintain a helpful and professional tone.

Parameters Mapping for update_video_config:
- script: The FULL text of the script in the specified format (no markdown symbols).
- visualType: AI_VIDEOS, AI_IMAGES, or STOCK_VIDEOS.
- visualStyle: Any descriptive style like 'Cinematic', 'Anime', 'Realism', etc.
- aspectRatio: '16:9', '9:16', or '1:1'.
- voiceId: If the user asks for a specific voice, use its ID.
- duration: '30', '45', or '60'.
- quality: 'regular' or 'high'.
- captionPosition: 'top', 'middle', or 'bottom'.
- captionSize: 'small', 'medium', or 'large'.`;

export const scriptToVideoFlow = ai.defineFlow(
  {
    name: 'scriptToVideoFlow',
    inputSchema: z.object({ message: z.string() }),
    outputSchema: z.object({ reply: z.string() }),
    streamSchema: z.string(),
  },
  async ({ message }, { sendChunk }) => {
    const { stream, response } = ai.generateStream({
      system: S2V_SYSTEM_PROMPT,
      config: {
        thinkingConfig: { thinkingBudget: 2000, includeThoughts: true },
      },
      prompt: `[USER]: ${message}`,
      tools: getScriptToVideoTools(),
    });

    const toolsQueue: Array<{
      id?: string;
      name: string;
      arg: any;
      response?: any;
    }> = [];

    for await (const chunk of stream) {
      if (chunk.text) {
        sendChunk(JSON.stringify({ event: 'text', text: chunk.text }));
      }

      if (chunk.role === 'model' && chunk.content?.[0]?.reasoning) {
        sendChunk(
          JSON.stringify({
            event: 'reasoning',
            text: chunk.content[0].reasoning,
          })
        );
      }
      if (chunk.role === 'model' && chunk.content) {
        for (let idx = 0; idx < chunk.content.length; idx++) {
          const tc = chunk.content[idx];
          if (tc.toolRequest) {
            const req = tc.toolRequest;
            const existing = toolsQueue.find((t) => {
              if (req.ref && t.id) return t.id === req.ref;
              return (
                t.name === req.name &&
                JSON.stringify(t.arg) === JSON.stringify(req.input)
              );
            });
            if (existing) {
              existing.arg = req.input;
              if (req.ref) existing.id = req.ref;
            } else {
              toolsQueue.push({ id: req.ref, name: req.name, arg: req.input });
            }
          }
        }
      }
      if (chunk.role === 'tool' && chunk.content) {
        for (let idx = 0; idx < chunk.content.length; idx++) {
          const tc = chunk.content[idx];
          if (tc.toolResponse) {
            const res = tc.toolResponse;
            const tool = toolsQueue.find((t) => {
              if (res.ref && t.id) return t.id === res.ref;
              return t.name === res.name && t.response === undefined;
            });
            if (tool) tool.response = res.output;
          }
        }
      }
    }

    for (const tool of toolsQueue) {
      sendChunk(
        JSON.stringify({
          event: 'tool',
          name: tool.name,
          arg: tool.arg,
          response: tool.response,
        })
      );
    }

    const { text } = await response;
    return { reply: text };
  }
);
